actors:
  kzhrk:
    image_url: /images/actors/kzhrk.jpg
    name: kzhrk
    url: https://twitter.com/kzhrk0430
  uematsu:
    image_url: /images/actors/default.png
    name: uematsu
    url: https://twitter.com/shotauematsu
author: Kazuhiro Kobayashi - info@kzhrk.com
description: インターネットを巻き戻すPodcast
description_long: 古き良きインターネットを取り戻すためにインターネットまわりのことを雑談するPodcast
email: info@kzhrk.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: G-LZ3933GFBF
hashtag: makimodo
itunes_podcast_url:
keywords: kzhrk,インターネット,podcast,makimodo,インターネットを巻き戻すPodcast
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: インターネットを巻き戻すPodcast
url: https://www.makimodo.net
