actors:
  kzhrk:
    image_url: /images/actors/kzhrk.jpg
    name: kzhrk
    description: |
      Frontend engineer.
      Podcast内では「かっぴ」「コバさん」の愛称で呼ばれている。
    links:
      - name: Twitter
        url: https://twitter.com/kzhrk0430
      - name: GitHub
        url: https://github.com/kzhrk
      - name: kzhrk.dev
        url: https://kzhrk.dev
  uematsu:
    image_url: /images/actors/uematsu.jpg
    name: uematsu
  goto:
    image_url: /images/actors/goto.png
    name: goto
author: Kazuhiro Kobayashi - info@kzhrk.com
description: インターネットを巻き戻すPodcast
description_long: 古き良きインターネットを取り戻すためにインターネットまわりのことを雑談するPodcast
email: info@kzhrk.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
  - audio
google_analytics:
hashtag: makimodo
itunes_podcast_url: https://podcasts.apple.com/jp/podcast/%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%8D%E3%83%83%E3%83%88%E3%82%92%E5%B7%BB%E3%81%8D%E6%88%BB%E3%81%99podcast/id1554626944
google_podcast_url: https://podcasts.google.com/feed/aHR0cHM6Ly93d3cubWFraW1vZG8ubmV0L2ZlZWQueG1s
keywords: kzhrk,インターネット,podcast,makimodo,インターネットを巻き戻すPodcast
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: インターネットを巻き戻すPodcast
url: https://makimodo.net
